version: "3.9"

services:

  backend:
    image: python:3.11

    working_dir: /app

    volumes:
      - ./backend:/app

    command: bash -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000"

    ports:
      - "8000:8000"

    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15

    environment:
      POSTGRES_USER: isp
      POSTGRES_PASSWORD: isp123
      POSTGRES_DB: ispdb

    ports:
      - "5432:5432"

  redis:
    image: redis:7

    ports:
      - "6379:6379"
